# Generated by Django 4.2.1 on 2023-06-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        ('payment_management', '0004_remove_payment_payment_id_alter_payment_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('history', models.TextField(blank=True, null=True)),
                ('Rwallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fwallet', to='payment_management.wallet')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fwallet', to='user_auth.userprofile')),
            ],
        ),
    ]
