# Generated by Django 4.2.1 on 2023-06-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakewallet',
            name='Rwallet',
        ),
        migrations.AddField(
            model_name='fakewallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='social.fakewallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn', to='social.fakewallet')),
            ],
        ),
    ]
